### ISSUE TITLE
Add delay

### ISSUE THREAD

**Issue by pcktm** [ericrosenbaum/makeymakey-capsense-keyboard#1]
Hello. When i touch lightly it almost always outputs two characters instead of one. Can you add just a little bit of delay before outputting the second character just like in normal keyboard?

**Comment by ericrosenbaum** [comment]
The operating system handles the rate at which characters repeat when you hold a key down, so it's worth checking that (you can increase the delay in a control panel). 

My guess is that that is not the problem though. It might be that what you are seeing is that the capsense code sending multiple very fast press and release events. One cause for this could be that there is some electrical noise affecting the sensing, making it fluctuate rapidly. You might try connecting or disconnecting your power adapter to see if that changes the behavior. 

One way to improve the stability of the sensing is to increase the values in the capThresholds array, from 1 to 2 or 3 or higher. This will require a higher capacitance value to trigger, so you might need a larger surface area, a more conductive material, a harder press, a wetter finger, etc. to trigger it, but it should be more reliable.

Another solution might be to add a short delay to the end of the loop function, for example by adding the line:

`delay(50);`

This will slow down the whole system, adding a bit latency to it.
